name: Build & Release Plugin

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build_release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Build and Package
        shell: pwsh
        run: |
          dotnet build --configuration Release -o ./Release

          $pluginJson = Get-Content ./Release/plugin.json | ConvertFrom-Json
          $version = $pluginJson.Version

          $tagName = if ("${{ github.event.release.tag_name }}") { "${{ github.event.release.tag_name }}" } else { "v$version" }
          $zipName = "Flow.Launcher.Plugin.Downloader.zip"

          # 4. Zip the publish folder
          Compress-Archive -Path ./Release/* -DestinationPath $zipName

          echo "ZIP_NAME=$zipName" >> $env:GITHUB_ENV
          echo "TAG_NAME=$tagName" >> $env:GITHUB_ENV

      - name: Upload/Update Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ZIP_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
